#! /bin/bash

#Necessary aliases

alias vi="sudo vi"
alias k="kubectl"

#Downloading scripts, giving the right permissions and executing it
curl https://raw.githubusercontent.com/Ayobama/Documentations/master/ec2_minikube.sh -o ec2.sh

chmod +x ./ec2.sh

./ec2.sh

#repeat the git clone all the way down to installing nginx
echo "Setting current user to have administrative permissions to run docker commands"

sudo usermod -aG docker ubuntu && newgrp docker

echo "Cloning Dick Chesterwood Istio Fleetmans' course"

git clone https://github.com/DickChesterwood/istio-fleetman.git

sleep 5

echo "Start Minikube"

minikube start --driver=docker --memory 4096

echo "Changed working directory to Course files"

cd istio-fleetman/_course_files

cd _course_files/

cd 1\ Telemetry/

kubectl apply -f 1-istio-init.yaml 

kubectl apply -f 2-istio-minikube.yaml

kubectl apply -f 3-kiali-secret.yaml 

kubectl apply -f 4-label-default-namespace.yaml

kubectl apply -f 5-application-no-istio.yaml

#configuring nginx

#sudo vi /etc/nginx/nginx.conf

echo "Configure portforwarding instead"

echo "kubectl port-forward <pod_name> <upstream_port>:<source_port>"

echo Completed!




