name: .cicd

on:
  push:

env:
  ARTIFACT_ID: nipinward
  DOTBANK_DEPLOYER: ${{ secrets.DOTBANK_DEPLOYER }}
  DOTBANK_DEPLOYER_PASSWORD: ${{ secrets.DOTBANK_DEPLOYER_PASSWORD }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql/mysql-server:5.7
        ports:
          - "3306:3306"
        env:
          MYSQL_USER: nipinward
          MYSQL_PASSWORD: nipinward
          MYSQL_DATABASE: nip
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      redis:
        image: redis
        ports:
          - "6379:6379"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: jdk17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          cache: "maven"
          distribution: "adopt"
      - name: test
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          bash .mvn/sonar.sh
  build:
    name: build
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        name: checkout
      - name: jdk17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          cache: "maven"
          distribution: "adopt"
      - name: build
        run: |
          bash .mvn/publish.sh
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/')
    needs:
      - build
    steps:
      - name: Webhook Deploy
        uses: joelwmale/webhook-action@master
        with:
          url: http://${{ secrets.CBA_MS_TEST_URL }}/hooks/deploy
          body: '{"service": "${{ env.ARTIFACT_ID }}", "version": "${{ github.ref_name }}" }'
      - name: slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ${{ github.ref_name }} deployed to test environment ':rocket:'
          SLACK_TITLE: ${{ env.ARTIFACT_ID }} deployed
          SLACK_USERNAME: Deployment
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
